# Generated by Django 4.2.4 on 2023-09-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
    ]
