# Generated by Django 4.2.4 on 2023-09-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_menu_category_id_remove_menu_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
